version: "3"

services:
  mysql:
    restart: always
    container_name: mysql
    build:
      context: ./mysql
      args:
        - MYSQL_USER=user
        - MYSQL_PASSWORD=password
        - MYSQL_ROOT_PASSWORD=password
    command: --init-file /home/init.sql
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - 13306:3306
    cap_add:
      - SYS_NICE # CAP_SYS_NICE

  node:
    restart: always
    container_name: node
    build:
      context: ./node
    working_dir: /home/app
    command: "/bin/sh -c 'npm install && npm start'"
    volumes:
      - ./src:/home/app
    ports:
      - 13000:3000

  redis:
    restart: always
    container_name: redis
    build:
      context: ./redis
    volumes:
      - redis_data:/home
    ports:
      - 16379:6379

volumes:
  mysql_data:
  redis_data:
